### ISSUE TITLE
Fix the specification of the accesors

### ISSUE THREAD

**Issue by gnzlbg** [gnzlbg/inline_vector#9]
From Casey's feedback:

> Again, missing operational semantics. If your intent is to pick up the meaning of some of these operations from the general sequence container requirements - and I think that's a good idea - you need to specify somewhere early in the specification that inline_vector<T, C> meets the sequence container requirements in [sequence.reqmts] except where otherwise specified.
> 
> data() == begin() == end() is only well-defined if iterator and pointer are the same type.

**Comment by gnzlbg** [comment]
@CaseyCarter 

I've specified that `inline_vector` models `ContiguousContainer` and its iterators model `ContiguousIterator`. Is:

> `data() == begin() == end()` 

well-defined in this case? Or should I do something like: `data() == std::addressof(*begin()) == std::addressof(*end())` or  `data() == std::pointer_from(begin()) == std::pointer_from(end())` ?

**Comment by CaseyCarter** [comment]
The Standard does not require contiguous iterators to be equality comparable with pointers. If you don't require your iterators to be equality comparable with pointers either - a cursory scan tells me that `iterator` and `const_iterator` are implementation-defined, but nothing more specific that that - then `data() == begin()` is not required to be well-formed. Also be aware that there is no `std::pointer_from`. I would suggest making `data()` unspecified when the container is empty and otherwise `data() == std::addressof(*begin())`.

The standard specifies that `vector::data` returns "A pointer such that `[data(), data() + size())` is a valid range. For a non-empty vector, `data() == addressof(front())`.
